# Generated by Django 3.2.5 on 2021-07-17 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tblAdvtBsc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbladvtbsc',
            name='FstAddTmst',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 18, 8, 17, 19, 11758)),
        ),
        migrations.AlterField(
            model_name='tbladvtbsc',
            name='LastUptTmst',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 18, 8, 17, 19, 11758)),
        ),
    ]
